### ISSUE TITLE
My translation content is HTML and is far greater than the max limit of google per request is there a solution for this in this module

### ISSUE THREAD

**Issue by adeel-raza** [Localize/node-google-translate#6]

**Comment by paton** [comment]
@adeel-raza 

Just migrated the library to use a POST request instead of GET. This increases the maximum input size from 2k characters to 5k characters.

The limit may actually be higher than 5k characters -- I was able to submit a 10k character translation successfully, although Google Translate docs quotes a 5k maximum.
